import React from "react";

const Page = () => {
  return (
    <div>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
      <p>profile</p>
    </div>
  );
};

export default Page;
